FROM ubuntu
RUN useradd pedro
EXPOSE 80
LABEL maintainer="PedroVaca"
RUN apt update 
RUN apt install nginx -y
RUN apt install curl --yes 
RUN apt install vim --yes
RUN apt update && apt install net-tools -y
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
WORKDIR /app
WORKDIR /tools
#COPY --chown=pedro:pedro --chmod=777 codigo.txt /app/
#COPY --chown=root:root --chmod=100 entrypoint.sh .
#ENTRYPOINT [ "./entrypoint.sh" ]
#CMD [ "XPTO" ]